# stack.yaml

# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
# ghc-9.4.8
resolver: lts-21.22

nix:
    packages: [ zlib ]

# User packages to be built.
packages:
- .
