# stack.yaml

# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver: lts-16.31

nix:
    packages: [ zlib ]

# User packages to be built.
packages:
- .
